mainSections = ["post", "elysia"]
rssFullContent = true
favicon = "img/favicon-elysia.png"

SortBy = "default"

[footer]
  since = 2026
  customText = ""

[dateFormat]
  published = ":date_full"
  lastUpdated = ":date_full"

[sidebar]
  compact = false
  emoji = ""
  subtitle = "新的一天，<br>从一场美妙的邂逅开始～♪"
  avatar = "img/avatar.png"

[article]
  headingAnchor = false
  math = false
  toc = true
  readingTime = true

[article.list]
  showTags = true

[article.license]
  enabled = true
  default = "Licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"

[widgets]
  homepage = [
    { type = "search" },
    { type = "archives", params = { limit = 5 } },
    { type = "categories", params = { limit = 10 } },
    { type = "tag-cloud", params = { limit = 10 } },
  ]
  page = [
    { type = "toc" },
  ]

[colorScheme]
  toggle = true
  default = "auto"

[cookies]
  enabled = false

[comments]
  enabled = false
