baseURL = 'https://yox1no.github.io/'
locale = 'zh-CN'
title = "Yox1no's Blog"
timezone = 'Asia/Shanghai'
theme = 'hugo-theme-stack'
defaultContentLanguage = "zh"
hasCJKLanguage = true

[outputs]
  home = ['HTML', 'RSS']

[pagination]
  pagerSize = 10

[permalinks]
  post = "/p/:slug/"
  page = "/:slug/"
